
import java.awt.Image;
import java.io.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import util.ConnectDB;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author R2D2
 */
public class MemberForm extends javax.swing.JInternalFrame {

    JFileChooser fileChooser = new JFileChooser();
    DefaultTableModel model1;
    Image img = null;
    String filePath = "";
    Connection con = null;
    Member mem;

    /**
     * Creates new form MemberForm
     */
    public MemberForm() {
        initComponents();
        String sql = "select * from customers";
        display(sql);
        mem = new Member();
    }

    void display(String sql) {
        model1 = (DefaultTableModel) cusTable.getModel();
        model1.setRowCount(0);
        con = ConnectDB.getConnection();
        int i = 0;
        //picture.setIcon(new ImageIcon(img));
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                String id = String.valueOf(rs.getInt("cus_id"));
                String fname = rs.getString("cus_fname");
                String lname = rs.getString("cus_lname");
                String age = String.valueOf(rs.getString("cus_age"));
                String gender = rs.getString("cus_gender");
                String address = rs.getString("cus_address");
                model1.addRow(new Object[]{fname, lname, age, gender, address});
                i++;
                //System.out.println(num+" : "+fname);  
            }
            if (i == 0) {
                JOptionPane.showMessageDialog(null, "Not Result");
                display(sql);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cusTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        fnameText = new javax.swing.JTextField();
        lnameText = new javax.swing.JTextField();
        ageText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        genderBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        newB = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        picture = new javax.swing.JButton();
        imageButton = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Member");

        cusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First name", "Last name", "Age", "Gender", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cusTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cusTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cusTable);
        if (cusTable.getColumnModel().getColumnCount() > 0) {
            cusTable.getColumnModel().getColumn(1).setResizable(false);
            cusTable.getColumnModel().getColumn(2).setResizable(false);
            cusTable.getColumnModel().getColumn(2).setPreferredWidth(7);
            cusTable.getColumnModel().getColumn(3).setResizable(false);
            cusTable.getColumnModel().getColumn(3).setPreferredWidth(10);
            cusTable.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        genderBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel1.setText("First Name:");

        jLabel2.setText("Last name:");

        jLabel3.setText("Age:");

        jLabel4.setText("Gender:");

        jLabel5.setText("Address:");

        idText.setEditable(false);
        idText.setBackground(new java.awt.Color(255, 255, 0));
        idText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idText.setForeground(new java.awt.Color(255, 0, 0));
        idText.setFocusable(false);

        jLabel6.setText("Member Id:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idText)
                    .addComponent(fnameText)
                    .addComponent(lnameText)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ageText, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addComponent(addressText))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressText)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10))
        );

        newB.setBackground(new java.awt.Color(255, 255, 255));
        newB.setText("New");
        newB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        picture.setFocusable(false);

        imageButton.setText("Browse");
        imageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageButtonActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search-20.png"))); // NOI18N

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(imageButton))
                    .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(49, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imageButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(newB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clear)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageButtonActionPerformed
        //fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            // user selects a file
            File selectedFile = fileChooser.getSelectedFile();
            if (result == JFileChooser.APPROVE_OPTION) {
                System.out.println("Selected file: " + selectedFile.getName());
                filePath = selectedFile.getName();
                try {
                    //TODO add your handling code here:
                    img = ImageIO.read(getClass().getResource("/image/" + filePath));
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
                picture.setIcon(new ImageIcon(img));

            }
            if (result == JFileChooser.CANCEL_OPTION) {
                try {
                    //TODO add your handling code here:
                    img = ImageIO.read(getClass().getResource("/user_male.png"));
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
                picture.setIcon(new ImageIcon(img));
            }
        }
    }//GEN-LAST:event_imageButtonActionPerformed

    private void newBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBActionPerformed
        // TODO add your handling code here:
        Member m = new Member();
        //int id = Integer.parseInt(idText.getText());
        String fname = fnameText.getText();
        String lname = lnameText.getText();
        String img = filePath;
        String gender = genderBox.getSelectedItem().toString();
        String addr = addressText.getText();
        int age = 0;
        if (ageText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Invalid Value");
        } else {
            age = Integer.parseInt(ageText.getText());
            if (fname.equals("") || lname.equals("") || age < 15 || age > 150 || addr.equals("")) {
                JOptionPane.showMessageDialog(null, "Invalid Value");
            } else {
                m.newMember(fname, lname, img, age, gender, addr);
                String sql = "select * from customers";
                display(sql);
            }
        }
        if (img.equals("")) {
            img = "defaultPic.png";
        }


    }//GEN-LAST:event_newBActionPerformed
    int selectRow = -1;
    int selectId = -1;
    private void cusTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusTableMouseClicked
        // TODO add your handling code here:
        selectRow = cusTable.getSelectedRow();
        con = ConnectDB.getConnection();
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM customers");
            int i = 0;
            while (rs.next()) {
                if (selectRow == i) {
                    selectId = rs.getInt("cus_id");
                    String id = String.valueOf(rs.getInt("cus_id"));
                    String fname = rs.getString("cus_fname");
                    String lname = rs.getString("cus_lname");
                    String age = String.valueOf(rs.getString("cus_age"));
                    String gender = rs.getString("cus_gender");
                    String address = rs.getString("cus_address");

                    idText.setText(id);
                    fnameText.setText(fname);
                    lnameText.setText(lname);
                    ageText.setText(age);
                    genderBox.setSelectedItem(gender);
                    addressText.setText(address);
                    filePath = rs.getString("img");
                    if (filePath.equals("")) {
                        img = ImageIO.read(getClass().getResource("/image/defaultPic.png"));
                    } else {
                        img = ImageIO.read(getClass().getResource("/image/" + filePath));
                    }
                    picture.setIcon(new ImageIcon(img));
                }
                i++;
                //System.out.println(i);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            con = ConnectDB.closeConnection();
            System.out.println(selectRow);
        }

    }//GEN-LAST:event_cusTableMouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        idText.setText("");
        fnameText.setText("");
        lnameText.setText("");
        ageText.setText("");
        addressText.setText("");
        try {
            img = ImageIO.read(getClass().getResource("/image/defaultPic.png"));
            picture.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            Logger.getLogger(MemberForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clearActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        con = ConnectDB.getConnection();

        if (selectRow >= 0) {
            String fname = fnameText.getText();
            String lname = lnameText.getText();
            String img = filePath;
            int age = Integer.parseInt(ageText.getText());;
            String gender = genderBox.getSelectedItem().toString();
            String addr = addressText.getText();
            mem.UpdateMember(fname, lname, img, age, gender, addr, selectRow, selectId);
            display("SELECT * FROM customers");
            JOptionPane.showMessageDialog(null, "Data updated");
            idText.setText("");
            fnameText.setText("");
            lnameText.setText("");
            ageText.setText("");
            addressText.setText("");
             selectId = -1;
             selectRow = -1;
        } else {
            JOptionPane.showMessageDialog(null, "Please select data");
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        if (selectRow >= 0) {
           // model.removeRow(selectRow);
            mem.DeleteMember(selectId);
            idText.setText("");
            fnameText.setText("");
            lnameText.setText("");
            ageText.setText("");
            addressText.setText("");

            display("SELECT * FROM customers");
            JOptionPane.showMessageDialog(null, "data Deleted");
            selectId = -1;
            selectRow = -1;
        } else {
            JOptionPane.showMessageDialog(null, "Please select data");
        }
    }//GEN-LAST:event_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField ageText;
    private javax.swing.JButton clear;
    private javax.swing.JTable cusTable;
    private javax.swing.JButton delete;
    private javax.swing.JTextField fnameText;
    private javax.swing.JComboBox genderBox;
    private javax.swing.JTextField idText;
    private javax.swing.JButton imageButton;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField lnameText;
    private javax.swing.JButton newB;
    private javax.swing.JButton picture;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
